apiVersion: batch/v1
kind: Job
metadata:
    name: sylius-job
spec:
    template:
        spec:
            containers:
                - name: sylius-php
                  image: sylius-prod-php:latest
                  command: ["php", "bin/console", "doctrine:migration:migrate", "-y"]
            restartPolicy: Never
    backoffLimit: 1
