apiVersion: v1
kind: Secret
metadata:
    name: sylius-secret
type: Opaque
data:
    name: dmFsdWU=
#---
#apiVersion: v1
#kind: Pod
#metadata:
#    name: local-image-test
#spec:
#    containers:
#        - name: local-image-container
#          image: sylius-prod:latest
#          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: sylius-deployment
    labels:
        app: sylius
spec:
    replicas: 3
    selector:
        matchLabels:
            app: sylius
    template:
        metadata:
            labels:
                app: sylius
        spec:
            containers:
                -   name: sylius
                    image: sylius-prod:latest
                    imagePullPolicy: Never
                    ports:
                        -   containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: sylius-service
spec:
    selector:
        app: sylius
    type: LoadBalancer
    ports:
        -   protocol: TCP
            port: 80
            targetPort: 80
            nodePort: 30000
