apiVersion: apps/v1
kind: Deployment
metadata:
    name: sylius-deployment
    labels:
        app: sylius
spec:
    replicas: 3
    selector:
        matchLabels:
            app: sylius
    template:
        metadata:
            labels:
                app: sylius
        spec:
            containers:
                -   name: sylius
                    image: ferror/sylius-image:1.11
                    ports:
                        -   containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: sylius-service
spec:
    selector:
        app: sylius
    type: LoadBalancer
    ports:
        -   protocol: TCP
            port: 80
            targetPort: 80
            nodePort: 30000
---
apiVersion: v1
kind: Secret
metadata:
    name: sylius-secret
type: Opaque
data:
    name: value
