apiVersion: v1
kind: ConfigMap
metadata:
    name: sylius-config
data:
    APP_ENV: prod
    APP_DEBUG: 0
    APP_SECRET: super-secret-app
    DATABASE_URL: mysql://root:mysql@mysql-service/sylius
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: sylius-deployment
    labels:
        app: sylius
spec:
    replicas: 3
    selector:
        matchLabels:
            app: sylius
    template:
        metadata:
            labels:
                app: sylius
        spec:
            containers:
                -   name: sylius-php
                    image: sylius-prod-php:latest
                    envFrom:
                        -   configMapRef:
                                name: sylius-config
                    imagePullPolicy: Never
                    ports:
                        -   containerPort: 9000
                -   name: sylius-nginx
                    image: nginx:latest
                    ports:
                          -   containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: sylius-service
spec:
    selector:
        app: sylius
    type: LoadBalancer
    ports:
        -   protocol: TCP
            port: 80
            targetPort: 80
            nodePort: 30000
