apiVersion: v1
kind: Service
metadata:
    name: mysql-service
    labels:
        app: mysql
spec:
    clusterIP: None
    selector:
        app: mysql
    ports:
        -   protocol: TCP
            port: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mysql-statefulset
spec:
    replicas: 1
    serviceName: mysql-service
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            terminationGracePeriodSeconds: 10
            containers:
                -   name: mysql
                    image: mysql:8.0
                    ports:
                        -   protocol: TCP
                            containerPort: 3306
                    env:
                        -   name: MYSQL_ROOT_PASSWORD
                            value: mysql
                    volumeMounts:
                        -   name: mysql-pv
                            mountPath: /var/lib/mysql
    volumeClaimTemplates:
        -   metadata:
                name: mysql-pv
            spec:
                storageClassName: localstorage
                accessModes:
                    - ReadWriteOnce
                resources:
                    requests:
                        storage: 1Gi
