apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-pv
spec:
    storageClassName: localstorage
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/tmp/kubernetes/mysql"
