apiVersion: v1
kind: Service
metadata:
    name: nginx-service
spec:
    selector:
        app: nginx
    type: LoadBalancer
    ports:
        -   protocol: TCP
            port: 80
            targetPort: 80
            nodePort: 30000 # Between 30 000 and 32 767
