apiVersion: batch/v1
kind: Job
metadata:
    name: {{ include "sylius.fullname" . }}-job
    labels:
      {{- include "sylius.labels" . | nindent 4 }}
spec:
    backoffLimit: 1
    template:
        metadata:
            labels:
            {{- include "sylius.fullname.selectorLabels" . | nindent 8 }}
        spec:
            containers:
                - name: {{ .Chart.Name }}
                  image: "{{ .Values.image.repository_app }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  command: ["php", "bin/console", "doctrine:migration:migrate", "-y", "--no-interaction"]
                  envFrom:
                      - secretRef:
                          name: {{ include "sylius.fullname" . }}-envs
            restartPolicy: {{ .Values.job.restartPolicy }}
