kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "sylius.fullname" . }}-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "sylius.fullname" . }}-sessions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
