name: Lint and Test Charts

on:
    push:
    pull_request:

jobs:
    lint-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

#            - name: Set up Helm
#              uses: azure/setup-helm@v3
#              with:
#                  version: v3.9.2

            - uses: actions/setup-python@v4
              with:
                  python-version: 3.7

            - name: Set up chart-testing
              uses: helm/chart-testing-action@v2.3.0

#            - name: Run chart-testing (lint)
#              run: ct lint --target-branch ${{ github.event.repository.default_branch }}

            - name: Create kind cluster
              uses: helm/kind-action@v1.3.0
              if: steps.list-changed.outputs.changed == 'true'

#            - name: Run chart-testing (install)
#              run: ct install
            - name: Run chart-testing (install)
              run: cd sylius/v2 && make deploy